server:
  port: 5000
  ssl:
    key-alias: sb2-recipes
    key-password: password
    key-store-password: password
    key-store-type: pkcs12
    key-store: classpath:sb2-recipes.pfx

spring:
  application:
    name: SERVICE-REGISTRY
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true