server:
  port: 9005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: ORDERS-SERVICE
  data:
    mongodb:
      database: ecommerce-orders
      password: password
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/ecommerce-orders
      username: root

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: true

