server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: PRODUCTS-SERVICE
  datasource:
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/ecommerce-products
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: true

