
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: SECURITY
  datasource:
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/ecommerce-security
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect